stages:
  - build
  - deploy
  - output

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - mkdir build
    - cd build
    - cmake -G "MinGW Makefiles" ..
    - cmake --build .
    - echo "Compile complete."
  tags:
    - win2012
  artifacts:
    expire_in: 1 h
    paths:
      - bin/

deploy-job:
  stage: deploy
  script:
    - echo "Deploying QT application..."
    - cd bin
    - windeployqt filesystem.exe
    - echo "Application successfully deployed."
  tags:
    - win2012
  artifacts:
    expire_in: 1 h
    paths:
      - bin/

output-job:
  stage: output
  script:
    - echo "Running output..."
    # - Compress-Archive -Path "./bin/*" -CompressionLevel Optimal -DestinationPath "./target.zip"
    - echo "Output ok."
  tags:
    - win2012
  artifacts:
    name: "filesystem"
    paths:
      - bin/