variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"
  LANGUAGE: "en_US.UTF-8"

before_script:
  - chcp 65001
  - $OutputEncoding = [System.Text.Encoding]::UTF8
  - git config --global i18n.commitEncoding utf-8
  - git config --global i18n.logOutputEncoding utf-8

stages:
  - build
  - deploy
  - output

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - mkdir build
    - cd build
    - cmake -G "MinGW Makefiles" ..
    - cmake --build .
    - echo "Compile complete."
  tags:
    - win2012
  artifacts:
    expire_in: 1 h
    paths:
      - bin/

deploy-job:
  stage: deploy
  script:
    - echo "Deploying QT application..."
    - cd bin
    - windeployqt filesystem.exe
    - cp "C:\Qt\6.7.2\mingw_64\bin\libgcc_s_seh-1.dll" ".\"
    - cp "C:\Qt\6.7.2\mingw_64\bin\libstdc++-6.dll" ".\"
    - cp "C:\Qt\6.7.2\mingw_64\bin\libwinpthread-1.dll" ".\"
    - echo "Application successfully deployed."
  tags:
    - win2012
  artifacts:
    expire_in: 1 h
    paths:
      - bin/

output-job:
  stage: output
  script:
    - echo "Running output..."
    # - Compress-Archive -Path "./bin/*" -CompressionLevel Optimal -DestinationPath "./target.zip"
    - echo "Output ok."
  tags:
    - win2012
  artifacts:
    name: "filesystem"
    paths:
      - bin/