stages:
  - build
  - deploy
  - test

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - mkdir build
    - cd build
    - cmake -G "MinGW Makefiles" ..
    - cmake --build .
    - echo "Compile complete."
  tags:
    - win2012
  artifacts:
    paths:
      - bin/

deploy-job:
  stage: deploy
  script:
    - echo "Deploying QT application..."
    - cd bin
    - windeployqt filesystem.exe
    - echo "Application successfully deployed."
  tags:
    - win2012
  artifacts:
    paths:
      - bin/

test-job:
  stage: test
  script:
    - echo "Running unit tests..."
    - sleep 1
    - echo "Test ok."
  tags:
    - win2012
  artifacts:
    paths:
      - bin/filesystem.exe