stages:
  - build
  - deploy
  - zip

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - mkdir build
    - cd build
    - cmake -G "MinGW Makefiles" ..
    - cmake --build .
    - echo "Compile complete."
  tags:
    - win2012
  artifacts:
    paths:
      - bin/

deploy-job:
  stage: deploy
  script:
    - echo "Deploying QT application..."
    - cd bin
    - windeployqt filesystem.exe
    - echo "Application successfully deployed."
  tags:
    - win2012
  artifacts:
    paths:
      - bin/

zip-job:
  stage: zip
  script:
    - echo "Running zip..."
    - Compress-Archive -Path "./bin/" -CompressionLevel Optimal -DestinationPath "./target.zip"
    - echo "Zip ok."
  tags:
    - win2012
  artifacts:
    paths:
      - target.zip